In [15]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix

    def T(self):
        _len = len(self.matrix)
        t_matrix = [[0 for i in range(_len)] for i in range(_len)]

        for i in range(_len):
            for j in range(_len):
                t_matrix[j][i] = self.matrix[i][j]

        return Matrix(t_matrix)

    def __add__(self, other):
        if isinstance(other, (int | float)):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] + other)
                result_matrix.append(row)
            return Matrix(result_matrix)
        elif isinstance(other, Matrix):
            result_matrix = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] + other.matrix[i][j])
                result_matrix.append(row)
            return(result_matrix)
    
    def __sub__(self, other):
        result_matrix = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] - other.matrix[i][j])
            result_matrix.append(row)
        return(result_matrix)

    def __matmul__(self, other):
        if len(self.matrix[0]) != len(other.matrix):
            raise ValueError("Количество столбцов первой матрицы должно быть равно количеству строк второй матрицы")
        result_matrix = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(other.matrix[0])):
                val = 0
                for k in range(len(other.matrix)):
                    val += self.matrix[i][k] * other.matrix[k][j]
                row.append(val)
            result_matrix.append(row)
        return(result_matrix)
    
    def __truediv__(self, other):

        # def find_inverse_matrix(self, matrix):
        #     m_len = len(self.matrix)
            # matrix_e = [[0.0] * _len for i in range(_len)]
            # for i in range(_len):
            #     matrix_e[i][i] = 1.0
            
            # extempted_matrix = [row + [0] * m_len for row in matrix]
            # for i in range(m_len):
            #     extempted_matrix[i][m_len + i] = 1

            # for i in range(m_len):
            #     max_row = i
            #     for j in range(i+1, m_len):
            #         if abs(extempted_matrix[j][i]) > abs(extempted_matrix[max_row][i]):
            #             max_row = j
            #     extempted_matrix[i], extempted_matrix[max_row] = extempted_matrix[max_row], extempted_matrix[i]

            #     max_num = extempted_matrix[i][i]
            #     for j in range(i, m_len * 2):
            #         extempted_matrix[i][j] /= max_num   #делаем дмагональные элементы равынми 1

            #     for j in range(m_len):
            #         if j != i:
            #             num = extempted_matrix[j][i]
            #             for k in range(i, m_len * 2):
            #                 extempted_matrix[j][k] -= num * extempted_matrix[i][k]

            # inverse_matrix = [row[m_len:] for row in extempted_matrix]

            # return inverse_matrix 
        

        # result_matrix = []
        # inverse_matrix = find_inverse_matrix(other.matrix)
        # for i in range(len(self.matrix)):
        #     row = []
        #     for j in range(len(inverse_matrix)):
        #         val = 0
        #         for k in range(len(inverse_matrix)):
        #             val += self.matrix[i][k] * inverse_matrix[k][j]
        #         row.append(val)
        #     result_matrix.append(row)
        # return(result_matrix)
        result_matrix = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] / other.matrix[i][j])
            result_matrix.append(row)
        return(result_matrix)
    
    def __mul__(self, other):
        result_matrix = []
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append(self.matrix[i][j] * other.matrix[i][j])
            result_matrix.append(row)
        return(result_matrix)

    def __eq__(self, other):
        result_matrix = []
        if isinstance(other, Matrix):
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[0])):
                    row.append(self.matrix[i][j] == other.matrix[i][j])
                result_matrix.append(row)
            return(result_matrix)
        else:
            return False
        
    def __repr__(self):
        return str(self.matrix)
            







In [16]:
class Test:
    array = [[1, 2, 3], [1, 2, 3]]
    
    def __repr__(self):
        return str(self.array)
    
t = Test()
t

[[1, 2, 3], [1, 2, 3]]

In [17]:
d3_array1 = [[2, 3, 4],
             [4, 3, 1],
             [7, 5, 9]]
d3_array2 = [[4, 4, 5],
             [8, 6, 4],
             [1, 5, 7]]

my_matrix1 = Matrix(d3_array1)
my_matrix2 = Matrix(d3_array2)

np_matrix1 = np.array(d3_array1)
np_matrix2 = np.array(d3_array2)

((my_matrix1 + 13.2) == (np_matrix1 + 13.2))
print((my_matrix1 + 13.2) == (np_matrix1 + 13.2))

print(my_matrix1 @ my_matrix2)
print(np_matrix1 @ np_matrix2)

False
[[36, 46, 50], [41, 39, 39], [77, 103, 118]]
[[ 36  46  50]
 [ 41  39  39]
 [ 77 103 118]]


In [18]:
%pip install -Uq numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import numpy as np

In [20]:
%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
%%ipytest

matrix1 = Matrix([[2, 3, 4],
           [4, 3, 1],
           [7, 5, 9]])
matrix2 = Matrix([[4, 4, 5],
           [8, 6, 4],
           [1, 5, 7]])
# number = 5


@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'
    
@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T().matrix == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

.F.F..F.F.                                                                                   [100%]
============================================ FAILURES =============================================
______________________________ test_matrix_add_number[matrix10-13.2] ______________________________

matrix1 = [[2, 3, 4], [4, 3, 1], [7, 5, 9]], number = 13.2

    @pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
    def test_matrix_add_number(matrix1: Matrix, number: int | float):
        assert (
            (matrix1 + number == np.array(matrix1.matrix) + number).all()
>       ), 'add section with matrix and number is not working right'
E       AttributeError: 'bool' object has no attribute 'all'

C:\Users\pozdn\AppData\Local\Temp\ipykernel_8224\246116495.py:20: AttributeError
______________________________ test_matrix_sub_number[matrix10-12.2] ______________________________

matrix1 = [[2, 3, 4], [4, 3, 1], [7, 5, 9]], number = 12.2

    @pytest.mark.parametrize("matrix1,n

In [42]:
a = np.array([1, 2, 3])
b = np.array([1, 3, 3])

(a == b).all()

False